source 'https://rubygems.org'

ruby '1.9.3'

# if ENV["JRUBY"]
#   ruby '1.9.3', engine: 'jruby', engine_version: '1.7.4'

#   # Server requirements
#   gem 'trinidad', '1.4.4', :platform => 'jruby'

#   platforms :jruby do
#     gem 'jruby-openssl'
#     gem 'json-jruby'
#   end
# else
#   ruby '1.9.3'
# end

gem 'puma', "~>2.13.4"

# Project requirements
gem 'rake'
gem 'sinatra-flash', :require => 'sinatra/flash'

gem 'activeresource', "~>3.2.9.rc2", :require => 'active_resource'

# Component requirements
gem 'haml'

# Test requirements
gem 'rspec', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"

# Padrino Stable Gem
gem 'padrino', '0.11.2'

gem 'rack-mobile-detect'

gem 'newrelic_rpm'

gem 'shorturl'

gem 'sass'

gem 'dotenv'

gem "autoprefixer-rails", "5.2.1.3"

gem 'pdfkit', "0.8.2"

gem 'roo', '~> 2.5.0'
# gem 'wkhtmltopdf-binary'



gem 'omniauth'
gem 'omniauth-facebook', '1.3.0'
gem 'omniauth-twitter'

gem 'aws-s3'
gem 'dalli'
gem 'rest_client'
gem 'cloudinary'
gem 'samlr'

gem 'firebase_token_generator'
gem 'metainspector'

gem 'iso8601', '0.8.7'
gem 'link_thumbnailer', '2.5.0'
gem 'therubyracer'

gem 'firebase'
